### ISSUE TITLE
Condense image upload routes to one route

### ISSUE THREAD

**Issue by thisiskennyb** [thisiskennyb/boulder_comp#159]
Currently there are three separate routes to upload an image for teams, leagues, and the user. 

Components:
- SelectLeagueImage path="/select-league-image/:leagueId"
- SelectTeamImage path="/select-team-image/:teamId"
- SelectAvatar path="/select-avatar-image/:userId"

We want to condense this to a single route to practice DRY. The challenge will be passing the id with useParams and the component recognizing if it is a league id, team id, or user id. 

Our idea is to store three variables in context that are all boolean values set to false. If the user is trying to upload a photo to the team page then it will toggle the boolean value for team to true. The context value can then be used in the component to perform the appropriate tasks.

**Comment by successPhil** [comment]
Deleted Select Image Components and Created a Single component that handles all of the image uploads. Our front end view and backend view pass ID for userdashboard. This isn't needed and should be removed.

The userdashboard PUT method was changing the userdashboard ID when it uploaded the photos. Adjusted the view to not do that. View still needs to be refactored. PK is not necessary, and a better endpoint name is suggested.

Refactored the file structure for front end to be organized by features. So far added Team, League, Dashboard, and Utils.

Utils is for smaller features that get used in multiple places. Grade Bars and Image Upload components are good example.
